export const cards = [
    {
      id: 1,
      nombreJoya: "Collar de gemas de lujo",
      precio: "$168.76",
      imagen: "../assets/img/pl-imag-1.jpeg",
      categoria: "Collares",
    },
    {
      id: 2,
      nombreJoya: "Anillo Aurora",
      precio: "$125.28",
      imagen: "../assets/img/pl-imag-2.jpeg",
      categoria: "Anillos",
    },
    {
      id: 3,
      nombreJoya: "Collar Reflejos",
      precio: "$620.73",
      imagen: "../assets/img/pl-imag-3.jpeg",
      categoria: "Collares",
    },
    {
      id: 4,
      nombreJoya: "Anillo infinito de ensueño",
      precio: "$327.71",
      imagen: "../assets/img/pl-imag-4.jpeg",
      categoria: "Anillos",
    },
    {
      id: 5,
      nombreJoya: "Anillo de joyas opulentas",
      precio: "$168.76",
      imagen: "../assets/img/pl-imag-5.jpeg",
      categoria: "Anillos",
    },
    {
      id: 6,
      nombreJoya: "Aretes Solitario Sereno",
      precio: "$125.28",
      imagen: "../assets/img/pl-imag-6.jpeg",
      categoria: "Aretes",
    },
    {
      id: 7,
      nombreJoya: "Aretes de halo atemporales",
      precio: "$620.73",
      imagen: "../assets/img/pl-imag-7.jpeg",
      categoria: "Aretes",
    },
    {
      id: 8,
      nombreJoya: "Aretes exquisitos",
      precio: "$327.71",
      imagen: "../assets/img/pl-imag-8.jpeg",
      categoria: "Aretes",
    },
    {
      id: 9,
      nombreJoya: "Anillo de elegancia atemporal",
      precio: "$168.76",
      imagen: "../assets/img/pl-imag-9.jpeg",
      categoria: "Anillos",
    },
    {
      id: 10,
      nombreJoya: "Anillo de encantos de lujo",
      precio: "$620.73",
      imagen: "../assets/img/pl-imag-10.jpeg",
      categoria: "Anillos",
    },
    {
      id: 11,
      nombreJoya: "Anillo de floración dichosa",
      precio: "$620.73",
      imagen: "../assets/img/pl-imag-11.jpeg",
      categoria: "Anillos",
    },
    {
      id: 12,
      nombreJoya: "Anillo chispeante",
      precio: "$168.76",
      imagen: "../assets/img/pl-imag-12.jpeg",
      categoria: "Anillos",
    },
    {
      id: 13,
      nombreJoya: "Anillo reluciente",
      precio: "$168.76",
      imagen: "../assets/img/pl-imag-13.jpeg",
      categoria: "Anillos",
    },
    

]